auto: true

pygments: true
paginate: 8
permalink: /:title

title: blog.zhangtaifeng.com
url: http://blog.zhangtaifeng.com
feed: /atom.xml
author_info: <a href="http://blog.zhangtaifeng.com/">zhangtaifeng</a>
