auto: true

pygments: true
highlighter:rouge
paginate: 8
permalink: /:title

title: 熊猫技术博客 
url: http://www.zhangtaifeng.com
feed: /atom.xml
author_info: <a href="http://www.zhangtaifeng.com/">zhangtaifeng</a>
